### ISSUE TITLE
백준 12851 숨바꼭질2 제 스파게티를 예뻐해 주실 분을 구합니다.

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/just-do-algorithms#127]
https://www.acmicpc.net/problem/12851

저는 최소 시간을 bfs로 구하고, 최소 시간 일 때 count(최소 시간 내 도착 가능한 경우의 수)를 따로 구하고자 했습니다.
그래서 비효율적이지만 bfs 메서드를 만들었는데요,
40퍼센트를 넘어갈 때 틀렸습니다가 떠버리네요..
반례를 찾아주시거나 코드를 개선해주시면 감사하겠습니다.

제 스파게티를 예뻐해 주시고 꼬인 코드를 풀어주신 분께 초콜릿 드립니다.

```java
package boj_12851_숨바꼭질2;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.LinkedList;
import java.util.Queue;
import java.util.StringTokenizer;

// 1차원 배열에서 BFS 탐색을 진행한다.
// N이 갈 수 있는 곳은 3곳이다. 현재위치에서 -1, +1, *2 
// BFS로 이 3개를 for문 돌려서 탐색한다
// 방문체크, 카운트용으로 visited 배열을 사용

public class Main {
	static int N, K, count, time;
	static int visited[];
	static Queue<Integer> queue;

	public static void main(String[] args) throws IOException {

		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		StringTokenizer st = new StringTokenizer(br.readLine()); // 한줄에 들어온 문자열을 나눈다
		N = Integer.parseInt(st.nextToken());
		K = Integer.parseInt(st.nextToken());

//		System.out.println(N);
//		System.out.println(K);

		if (N == K) {
			System.out.printf("0\n1"); // 같은 위치에서 시작 시 0 1을 출력
		} else {
			visited = new int[100001];
			time = 0;

			visited = new int[100001];
			count = 0;
			BFS();

			System.out.printf("%d\n%d", time, count);
		}
	}

	static void BFS() {
		queue = new LinkedList<>();
		queue.add(N);
		visited[N] = 1;

		while (!queue.isEmpty()) {
			int now = queue.poll();

			for (int i = 0; i < 3; i++) {
				int next;
				if (i == 0) {
					next = now + 1;
				} else if (i == 1) {
					next = now - 1;
				} else {
					next = now * 2;
				}
				if (next == K && time == 0) {
					time = visited[now];
				}

				if (next == K && visited[now] == time) {
					count++;
				}

				if (next < 0 || next > 100000) {
					// 범위 벗어나면 스킵
					continue;
				}
				if (visited[now] > time && visited[next] != 0) {
					// 방문한 노드는 스킵
					continue;
				}

				queue.add(next);
				visited[next] = visited[now] + 1;
			}

		}
	}

}


```

**Comment by clare-u** [comment]
반례를 하나 찾았는데요, 

입력: 0 3
제 출력 : 
3
1
정답: 
3
2

어느 조건문이 문제인 걸까요

**Comment by qkrrjsxor** [comment]
정확히 어떤 부분에서 문제인지는 모르겠는데, 한번 방문한 노드를 다 스킵해버리면 같은 루트를 일부 공유하는 최소 시간을 모두 카운트 할 수 없는것 같습니다.

예를들면 0 3 이면
0 +1
1 +1
2 +1
3

0 +1
1 x 2
2 +1
3
이 두가지 경우가 있는데
visited != 0 일 때 스킵을 해버리면 두번째 경우에서 visited[1] 이랑 visited[2] 가 0이 아니게돼서 둘다 최소 시간인데도 아래 경로는 고려하지 않게 된다

**Comment by celestedayoung** [comment]
윗 분이 말씀하신 것과 같이 중복 방문을 허용해야 하는 조건을 고려해보세요!

**Comment by Glenn-syj** [comment]
해당 코드에서 위 반례에 대해 잘못된 값을 출력하는 까닭은 문제의 상황에 맞지 않는 코드이기 때문입니다. 이는 단순히 조건문의 문제가 아니라, BFS 내 로직의 문제입니다.

예를 들어 `0 3`이 입력으로 주어지는 경우를 생각해봅시다. 그러면 다음과 같은 순서가 나올 수 있겠습니다.

`0 -> 0 + 1 = 1 -> 1 * 2 = 2 -> 2 + 1 = 3 (K)`
`0 -> 0 + 1 = 1 -> 1 + 1 = 2 -> 2 + 1 = 3 (K)`

그러나 위의 경우에서, for 문 내의 로직을 따르면 아래 결과에 대한 값만 인정이 됩니다. 이유는 바로 아래 코드 때문입니다.

```java
if (visited[now] > time && visited[next] != 0) {
	// 방문한 노드는 스킵
	continue;
}

queue.add(next);
visited[next] = visited[now] + 1;
```

`next`가 처음으로 2가 되었을 때, `visited[next]`의 값이 `visited[now]+1`이 됩니다. 그러면 자연스럽게 다음 코드에서는 **같은 거리/시간**에 있음에도 불구하고, `visited[next]`는 한 `now`에 대해서 0이 아니게 되어버립니다.

```java
static void BFS() {
		queue = new LinkedList<>();
		queue.add(N);
		visited[N] = 1;
		boolean check = false;

		while (!queue.isEmpty()) {
			int now = queue.poll();
			System.out.println("now: " + now + " visited[2]: " + visited[2]);

			for (int i = 0; i < 3; i++) {
				int next;
				
				
				if (check) {
					if (visited[now] > time) {
						break;
					}
				}
				
				if (i == 0) {
					next = now + 1;
				} else if (i == 1) {
					next = now - 1;
				} else {
					next = now * 2;
				}
				
				
				if (next == K && time == 0) {
					time = visited[now];
					check = true;
				}

				if (next == K && visited[now] == time) {
					count++;
				}

				if (next < 0 || next > 100000) {
					// 범위 벗어나면 스킵
					continue;
				}
				System.out.println("visited[now]: " + visited[now] + " time: " + time);
				if (visited[now] > time && visited[next] != 0) {
					System.out.println("skipped");
					// 방문한 노드는 스킵
					continue;
				}

				queue.add(next);
				visited[next] = visited[now] + 1;
			}

		}
	}
```

BFS 코드를 이와 같이 바꿔 보시면 아래처럼 결과가 나옵니다.

```java
0 3
now: 0 visited[2]: 0
visited[now]: 1 time: 0
visited[now]: 1 time: 0
skipped
now: 1 visited[2]: 0
visited[now]: 2 time: 0
visited[now]: 2 time: 0
skipped
visited[now]: 2 time: 0
skipped
now: 2 visited[2]: 3
visited[now]: 3 time: 3
visited[now]: 3 time: 3
visited[now]: 3 time: 3
now: 3 visited[2]: 3
now: 1 visited[2]: 3
now: 4 visited[2]: 3
3
1
```

여기에서 `visited[now]: 2 time: 0` 부분에서 맨 처음 `1+1`로 `2`가 되는 부분을 제외하고는 진입하지 않음이 발견됩니다.

**Comment by Glenn-syj** [comment]
또한, 원본 코드는 추가적인 개선점을 가지고 있는데요.

1. BFS의 종료 조건

사실 이 문제에서는 가장 처음으로 짧은 거리를 발견하게 되면, 이후 거리에 대해서는 작동하지 않아도 됩니다. 즉, 가장 처음으로 K가 되는 시간과 같은 시간 이후에는 탐색을 진행할 필요가 없습니다.

위 코드에서는 원본 코드를 살리려고 임시적으로 `check`를 추가했지만, 실제로 설계 구현 하실 때는 다른 방식을 찾아보셔도 좋겠습니다.

2. `int[][] visited`의 효용

사실 이 문제에서는 `int[][] visited`가 아니라 `boolean[][] visited`가 더욱 효율적으로 보입니다. 이는 앞서 말했듯이, 가장 처음으로 K가 되는 시간까지만 적용하면 되는 까닭입니다. 때로 `int[][]`를 이용한 방문 배열은 익숙하지 않다면 혼란을 발생시키기 쉬운 것 같습니다.

사실 논리적으로 생각해보면 쉽습니다. 여러 가능성 중 A -> B -> C -> A의 순서로 점을 이동한다고 생각해봅시다. 마지막 A에서는 다시금 B를 방문할 것인데, 그렇다면 필연적으로 이후의 A는 이전의 A보다 더 많은 탐색 횟수를 요구하게 될 것입니다. 따라서 이미 방문했던 점은 방문할 필요가 없는 셈입니다.

3. 언제 방문 체크를 끝낼 것인가?

BFS를 빠르게 이용하는 방법 중에는 queue에 요소를 추가할 때 `visited`의 값을 바꿔주는 방법이 있습니다. 하지만 이 문제에서, 이러한 접근은 타당하지 않게 보입니다.

왜냐하면, 같은 거리 내에서는 같은 점을 여러 번 방문할 수 있기 때문입니다. 하지만 `visited[next] = visited[now] + 1;`에서는 이미 방문체크가 되고 있습니다. 따라서 queue에 넣으면서 방문 체크를 하면 안된다는 점 역시 유의해야 합니다. 


---

저는 원본 코드를 떠나서, 아예 처음부터 로직을 새로 짜보시기를 권장드립니다. int[][] 배열이 잘 쓰면 효율적인 것은 맞지만, `visited`의 원 의미를 살려 `boolean[][]`으로 BFS를 이용하시는 연습을 더 해보셔도 좋겠습니다.

**Comment by clare-u** [comment]
한번 방문한 노드를 다 스킵하지 않고, 어떤 경우 중복 방문을 허용하는 조건을 추가해서 문제를 풀이했습니다. 처음부터 설계하기에는 time을 어떻게 구할지 아이디어가 떠오르지 않아, 조언을 듣고 저와 최대한 비슷한 로직으로 풀이했던 풀이를 peek한 게 큰 도움이 되었습니다. Week008에 md파일과 함께 게시하겠습니다 다들 감사합니다!
