### ISSUE TITLE
[백준 17404 RGB거리2] 시간 초과가 나는데 어디를 고쳐야 할지 모르겠습니다

### ISSUE THREAD

**Issue by qkrrjsxor** [Glenn-syj/just-do-algorithms#128]
[백준 17404 RGB거리2](https://www.acmicpc.net/problem/17404)

처음에 재귀를 이용한 조합으로 풀었다가 시간 초과가 나서, DP로 고쳐봤는데도 시간 초과가 발생했습니다.

애초에 제가 DP를 맞게 사용해서 푼 건지도 모르겠는데, 제가 한 방법이 DP가 맞는지 봐주시길 부탁드립니다.

- **내가 생각한 풀이** : 

우선 첫째 줄에 선택한 것을 마지막줄에선 선택을 못하는 조건이 있으므로, 첫재 줄은 따로 계산을 해서 dp[0] 에 넣어줬습니다.
첫째 줄에 선택한 열 인덱스를 first로 저장하고 재귀를 돌렸는데, dp 배열에는 이전 인덱스의 값에다가 이번 행에서 선택한 열 인덱스의 값을 더해주었습니다. ( dp[r] = dp[r-1] + arr[r][c] )

이번 행에서 선택한 값은 다음 행에서 선택하면 안되므로 재귀를 호출 할 때 이번 행에서 선택한 열 인덱스에 대해서는 continue 하여 스킵하고,  before 변수로 재귀 함수 인자로 넘겨주었습니다. 

 마지막 행(r = N-1)에 도달하면 이전에 선택한 열 인덱스(before 로 넘겨준 인자) 와 비교해서 선택 가능한 값을 더한 뒤에 ans 변수에 dp[N]의 최소값을 저장했습니다.

이 풀이가DP를 맞게 쓴 게 맞을까요?

```java
package boj_17404_박건택;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.StringTokenizer;

public class Main {
	static int[][] arr;
	static int first;
	static int sum;
	static int N;
	static int ans = Integer.MAX_VALUE;
	static int[] dp;

	public static void main(String[] args) throws IOException {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		StringTokenizer st;

		N = Integer.parseInt(br.readLine());

		arr = new int[N][3];
		dp = new int[N];
		for (int i = 0; i < N; i++) {
			st = new StringTokenizer(br.readLine());
			for (int t = 0; t < 3; t++) {
				arr[i][t] = Integer.parseInt(st.nextToken());
			}
		}

		for (int i = 0; i < 3; i++) {
			dp[0] = arr[0][i];
			first = i;

			for (int t = 0; t < 3; t++) {
				if (t == first)
					continue;
				sumCount(1, t, first);
			}
		}
		System.out.println(ans);
	}

	public static void sumCount(int r, int c, int before) {
		// base case
		if (r == N - 1) {   //마지막 행에 도착하면
			if (before == first) {      // 이전에 선택한 열 인덱스가 첫 행과 같으면 마지막행 두 값 중 작은값을 선택
				dp[r] = dp[r - 1] + Math.min(arr[r][(first + 1) % 3], arr[r][(first + 2) % 3]);
			} else {        //이전에 선택한 열 인덱스가 첫 행과 다르면 하나의 값만 선택가능하므로
				dp[r] = dp[r - 1] + arr[r][3 - (first + before)];
			}
			
			if(dp[r] < ans) {
				ans = dp[r];
			}
			return;
		}

		dp[r] = dp[r - 1] + arr[r][c];
		for (int i = 0; i < 3; i++) {
			if(i == c)     //이번에 선택한 열 인덱스는 패스
				continue;
			sumCount(r + 1, i, c);
		}

	}
}

```

**Comment by Glenn-syj** [comment]
### 시간 초과의 원인

해당 코드에서 시간 초과가 발생하는 가장 큰 이유는 재귀적으로 일단 모든 분기에 대해 접근하기 때문입니다. 즉, 적절하게 dp 배열을 사용하고 있지 않습니다. 우선, 해당 코드가 500 ms 제한과 얼마나 차이나는지 확인할 필요가 있습니다.

```java
long startTime = System.currentTimeMillis();
System.out.println("startTime: " + startTime);

for (int i = 0; i < 3; i++) {
	dp[0] = arr[0][i];
	first = i;

	for (int t = 0; t < 3; t++) {
		if (t == first)
			continue;
		sumCount(1, t, first);
	}
}
System.out.println(ans);
long endTime = System.currentTimeMillis();
System.out.println("endTime: " + endTime);
System.out.println("elapsedTime: " + (endTime-startTime));
```
원본 코드를 조금 수정해, 수행에 얼마나 걸리는지 측정해보았습니다.

```
27
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
```

위 입력에 대한 결과 값은 아래와 같습니다.

```
startTime: 1712126886403
27 // 답
endTime: 1712126887733
elapsedTime: 1330
```

27줄의 입력에도 수행에 1330ms가 걸리고 있습니다. (물론 출력과 관련된 시간은 보정될 필요가 있습니다.) 그렇다면 `N=1000`인 경우에는 볼 필요도 없겠습니다. 가장 중요한 이유는 Dynamic Programming을 적절하게 사용하고 있지 않은 까닭입니다.

1, `dp` 배열의 이용
원본 코드는 `dp` 배열을 백트래킹에서 이전 값을 저장하는 용도로만 쓰이고 있습니다. 즉, dp 배열은 사실 코드의 수행 시간을 줄이는데 크게 도움을 주지 않습니다. 이는 인자로 넘기는 것과 다를 바 없습니다.

2. 백트래킹의 사용
이 문제를 백트래킹으로 푸는 것은, 가능한 모든 분기에 접근하는 것과 다를 바 없습니다. 이전에 선택한 열에 대해서 접근하지 않는다 하더라도, 최악의 경우 시간 복잡도가 `O(2^N)`임은 동일합니다.

### 시간초과의 해결

시간 초과문제를 해결하기 위해서는, dp에 대해서 다르게 접근하는 방법이 필요합니다. 즉, 모든 경우의 수를 방문하지 않아야 합니다. 이러한 목표는 어떻게 달성될 수 있을까요?

해당 문제는 DP를 이용해, 각 출발점마다의 최소 값을 비교하도록 요구합니다. 출발점이 달라지면 경로 상에서의 최소 값도 달라진다는 점에 유의해야 합니다.

**Comment by qkrrjsxor** [comment]
저도 dp배열을 보면서 조합에서 코드랑 다를 바가 없다고 느꼈습니다.
dp 배열을 만들 때 최소값을 비교하며 대입하는 방법을 찾아보고 풀어보겠습니다!

**Comment by undeadtimo** [comment]
사실 17404번 문제를 저도 풀었으나, qkrrjsxor님의 질문에 답변을 못하는 저를 보고, dp에 대한 개념과 작동방식을 정확히 숙지하지 못하고 있다는 것을 알게 되었습니다.

Glenn-syj님의 답변을 보고 dp 문제를 풀 때 어디에 초점을 맞춰야하는지를 다시 생각해보게 되었습니다.

또한 프로그램의 수행시간을 측정할 수 있는 메서드에 대한 존재를 모르고 있었는데,
currentTimeMillis() 메서드를 알게되어 앞으로 수행시간이 중요한 문제에서 도움이 될 것 같습니다.
