### ISSUE TITLE
[알고리즘 학습법] 알고리즘 개념을 따로 공부하고자 하는데, 학습의 방향성에 대해 조언을 구합니다.

### ISSUE THREAD

**Issue by celestedayoung** [Glenn-syj/just-do-algorithms#152]
just-do-algorithms를 통해 알고리즘 문제 풀이 실력이 조금씩 향상하는 것을 느끼고 있습니다!
함께 해주시는 모든 분들께 먼저 감사의 말씀 드리고 싶네요.

요즘 저의 알고리즘 공부 방향성에 대해 재고해본 결과, 
스터디를 통해 문제를 풀며 개념을 익히고 복습하는 것만으로는 자꾸만 부족한 부분이 생기는 것 같다고 느꼈습니다.
기본적인 그래프 탐색이나, 문제에서 특정 알고리즘을 제시하는 경우를 제외하면 접근 방법이나 구현에 있어 어려움을 느낍니다.
결국 밑 빠진 독에 물 붓기라는 생각이 들어 **개념을 탄탄히 하는 방향으로 공부를 더 하고자 합니다**.

저는 평소에 영상보단 글을 통해 공부를 하는 편입니다. 
현재 [자료구조 책](https://product.kyobobook.co.kr/detail/S000001743851) 중 괜찮은 게 있어 해당 책으로 공부 중인데요, 
동일 저자의 [알고리즘 책](https://product.kyobobook.co.kr/detail/S000211830160)으로 알고리즘 개념들을 복습하는 것은 어떠한지 여쭙습니다.

또한 다른 분들은 알고리즘 문제 풀이 외 개념 공부를 어떻게 하고 계신지 궁금합니다.

**Comment by Glenn-syj** [comment]
저도 알고리즘이나 자료구조에 대해서는 기본기를 닦아야 잘 응용할 수 있다는 입장에 동의합니다.

문병로 교수님의 쉽게 배우는 ... 시리즈는 주변에서도 괜찮은 책이라는 말을 하더라구요. 공부하며 부족한 개념이나 심화적인 접근을 해버고 싶다면, 참고 서적으로 [CLRS](https://en.m.wikipedia.org/wiki/Introduction_to_Algorithms)를 추천합니다.

**Comment by celestedayoung** [comment]
괜찮은 책이라니 잘 골랐군요!! 말씀해주신 참고 서적도 챙겨보며 공부해보도록 하겠습니다. 조언 감사드립니다:D
