### ISSUE TITLE
[ALG-NONE] 코딩 테스트와 채용에 대해서

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/just-do-algorithms#190]
### 들어가며

진행하는 프로젝트 일정이 바빠질수록, 코딩 테스트 자체를 위한 알고리즘 공부를 향한 회의감 이곳 저곳에서 들려옵니다. 물론 코딩 테스트를 시행하는 기업에 입사하려는 구직자는 좋든 싫든 준비할 수 밖에 없기는 합니다. 하지만 그와 마찬가지로, 우리가 좋든 싫든 개발 공동체의 일원이라는 점에서, 채용 과정에서 알고리즘과 코딩 테스트가 어떤 역할을 하는지 생각해 볼 필요가 있습니다.

### 본론... 대신

사실 저 역시 취업을 준비하는 입장에서, 코딩테스트의 이러저러한 장단점을 논하기에는 무리가 있습니다. 실효성도 없고, 신뢰할 수도 없는 말이니까요. 대신 제가 자주 들여다보는 [HackerRank](https://news.ycombinator.com/)라는 사이트에서, 코딩 테스트와 관련된 글 하나를 가져왔습니다.

[Why I won't do coding tests](https://news.ycombinator.com/item?id=11420563)
(영어에 익숙하지 않다면, 언제나 구글 크롬 번역을!)

위 글을 그저 구직자-채용담당자나, 찬성파-반대파로만 나누어 읽을 필요는 없겠습니다. 취업 준비생은 둘 모두를 받아들일 수 있는 (혹은 받아들여야만 하는) 입장이니까요. 동시에 이는 결국 우리가 개발 생태계 혹은 개발팀의 일원이 되어, 언젠가 채용에 관여하게 될 때의 문제이기도 합니다. 모두 한 번 쯤 고민해봐도 좋겠습니다.

물론 한국 채용시장과 미국 채용시장은 구조가 다르다는 점을 인지해야 할 것입니다. 하지만 분명한 차이에도, 충분한 고민 거리를 얻어낼 수 있는 글입니다.

> These discussions are always frustrating, because both sides have perfectly sensible points.
From the employers' side: They really really really do get many candidates who cannot program at all. I've been on the hiring side and seen the applications, and the amount of worthless non-programmers out there is high. And it's not just for entry-level posts -- plenty of these people have a decade of experience and titles with "Senior" in them. A simple "can you write code" filter is absolutely essential for a hiring manager not to spend all their time interviewing terrible junk candidates.
>
> From the developer's side: If they're any good at all, they really really really can get hired by a company they want to work for very quickly and with little effort, and so their motivation to jump through hoops is going to be low. If ten companies want to hire me, and two of them want me to spend half a day doing coding problems, well, guess who I'm going to get back to last/never.
>
> The employers aren't stupid. The devs being interviewed aren't stupid. Everyone has totally sensible priorities.
>
> So this really just comes down to individual situations. If you as an employer are having a hard time finding people and you're requiring a coding test... maybe quit requiring it, see if you get a broader applicant pool. If you as a developer are having a hard time finding a job and are rejecting employers that require a test... well, suck it up and do some of the tests.
>
> But if a developer is happily employed or an employer is able to find good devs, well, maybe you've hit a good compromise point for now, but be willing to re-evaluate in the future.

**Comment by clare-u** [comment]
확실히 채용담당자 입장에서 코딩테스트의 존재가 어떤 이점을 가질지는 생각해 본 적 없었는데, 합리적인 결론을 내려준 글이네요.
