### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by ucream-sh** [Glenn-syj/just-do-algorithms#22]
# Week 2

### 공통 과제

- [ ]  백준 15828 큐2
https://www.acmicpc.net/problem/18258
- [ ]  SWEA 1244 최대 상금
[https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWVWgkP6sQ0DFAUO#none](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=4&contestProbId=AV15Khn6AN0CFAYD&categoryId=AV15Khn6AN0CFAYD&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=4&pageSize=10&pageIndex=1)

### 분할 과제

**하**

- [ ]  SWEA 7236 저수지의 물의 총 깊이 구하기
[https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PobmqAPoDFAUq](https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AWlTKTUqCN8DFAVS)
- [ ]  SWEA 11315 오목 판정
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXaSUPYqPYMDFASQ

**중**

- [x]  백준 15828 Router -> 박건택
[https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PjMgaALgDFAUq](https://www.acmicpc.net/problem/15828)
- [x]  백준 11399 ATM -> 황민욱
https://www.acmicpc.net/problem/11399
- [x]  SWEA 4408 자기 방으로 돌아가기 -> 유서현
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWNcJ2sapZMDFAV8

**상 (아닐수도)**

- [x]  백준 3190 뱀 -> celestedayoung
https://www.acmicpc.net/problem/3190
- [x]  SWEA 8888 시험 -> 송창용
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AW45RuSae2gDFAQ7

---

공통 과제가 2개라 좋네요! 저는 오늘안에 문제 고르도록 하겠습니다

**Comment by ucream-sh** [comment]
SWEA 4408 자기 방으로 돌아가기 의 설명 담당해보겠습니다

**Comment by celestedayoung** [comment]
백준 3190 뱀. 이제 이 문제는 제 것입니다.
![download](https://github.com/Glenn-syj/just-do-algorithms/assets/144453750/d7cdbe9f-fcfe-4e1c-9e06-26384f45632a)

**Comment by undeadtimo** [comment]
시험을 망친 기념으로 8888번 '시험' 문제를 풀어보도록 하겠습니다.
![웃긴짤](https://github.com/Glenn-syj/just-do-algorithms/assets/116619948/763bd84d-c70f-46b8-b267-0df851539333)

**Comment by qkrrjsxor** [comment]
구럼 나는 15828 Route

**Comment by Glenn-syj** [comment]
문제 풀면서 막히는 부분이나 반례를 못 찾겠어서 계속 틀린다면, 꼭
`problem solving` 태그를 포함해서 글을 작성해주세요
당연히 "[ALG-주차] 및 문제 플랫폼 문제 번호 질문 제목" 과 같은 형식이어야 합니다.

솔직히 같이 반례 찾아서 로직 고치는 것도 많은 도움이 되니 다들 못 풀거나 시간이 많이 걸린다고 부끄러워하지 말고 올려주세요!

**Comment by ucream-sh** [comment]
이번주도 고생하셨고 즐거운 설날 되시길 바랍니다!
