### ISSUE TITLE
SWEA_1224_계산기3 에서 후위연산자로 변경하는 과정이 잘 안되네요 도와주실분?

### ISSUE THREAD

**Issue by ucream-sh** [Glenn-syj/just-do-algorithms#24]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14tDX6AFgCFAYD

이 문제를 풀이 중입니다.

1. 입력받은 문자열을 후위연산식으로 변경 
2. 후위연산식으로 계산해서 값을 출력

하려는데 1 과정이 잘 되지 않고 있는 것 같습니다.

입력값으로 
```
11
3+(4+5)*6+7
```
을 넣으면

원래 나와야 할 코드는 `345+6*+7+` 인데
제 코드는 `345+6*7` 을 뱉어냅니다..

디버깅용 출력문 넣고 돌렸을 땐 
```
11
3+(4+5)*6+7
3는 계산식에 들어갔음
+를 push했다!
(를 push했다!
4는 계산식에 들어갔음
+를 push했다!
5는 계산식에 들어갔음
pop했다!
*를 push했다!
6는 계산식에 들어갔음
pop했다!
+를 push했다!
7는 계산식에 들어갔음
345+6*7
```
이렇게 나오는데요
pop을 한번 더 해야하는걸까요? 한다면 어디서 해야할지 뇌정지가 오네요

아래는 디버깅용 출력문을 넣은 제 코드입니다. 매우 기니까 스압 주의
http://colorscripter.com/s/HzC32Om

**Comment by Glenn-syj** [comment]
`System.out.println(stackTop);`
코드를 추가해보니 값이 0이 나오네요. 스택이 제대로 안 비워져있는 듯 합니다!

**Comment by Glenn-syj** [comment]
추가로 100행에 ')'가 '('를 만났기 전까지 모두 pop()하는 것은 맞지만, 이 반복이 끝나고 pop()을 한 번 더 해서 열린 괄호를 빼줘야 합니다.

**Comment by Glenn-syj** [comment]
그리고 메소드에 대한 디버깅 문구는 메소드 자체에 넣어 두면 해당 메소드가 실행될 겁니다.

**Comment by ucream-sh** [comment]
오 디버깅 문구를 메소드에 넣을 생각을 못했네요 너무 좋습니다!

이 반복이 끝나고 pop()을 한 번 더 해서 열린 괄호를 빼줘야 합니다. -> 라는 문구 56 행 말씀하신거로 이해했습니다. 다시 해보겠습니다.

**Comment by undeadtimo** [comment]
저도 똑같은 problem을 겪었는데요, 
반복문 돌리다가 마지막 요소를 탐색하는 경우에는 후기 표현식에 해당 요소를 추가해주는 형식으로 구현해주면 되지 않을까요?

**Comment by ucream-sh** [comment]
감사합니다 요정님들 
```
if (i == str.length() - 1) {
				calStr += pop(); // 계산식에 넣어주고 pop
				System.out.println("pop했다!");
			}
```


for 문 맨 마지막에 이거 추가하고 멀쩡하게 출력중입니다.
`345+6*+7+`
굿입니다

**Comment by ucream-sh** [comment]
```
for (int i = 0; i < ansArr.length; i++) {
			if ('0' <= ansArr[i] && ansArr[i] <= '9') { // 피연산자면
				push(ansArr[i]);
			} else if (ansArr[i] == '+') { // + 면
				int temp1 = pop() - '0';
				int temp2 = pop() - '0';
				push((char) (temp1 + temp2));
			} else if (ansArr[i] == '-') { // - 면
				int temp1 = pop() - '0';
				int temp2 = pop() - '0';
				push((char) (temp1 - temp2));
			} else if (ansArr[i] == '*') { // * 면
				int temp1 = pop() - '0';
				int temp2 = pop() - '0';
				push((char) (temp1 * temp2));
			} else if (ansArr[i] == '/') { // / 면
				int temp1 = pop() - '0';
				int temp2 = pop() - '0';
				push((char) (temp1 / temp2));
			}
			if (i == calStr.length() - 1) { // 수식이 끝나면
				System.out.println(pop());
			}
```
![image](https://github.com/Glenn-syj/just-do-algorithms/assets/156143681/f671d34b-621e-4199-9a07-7372c4eebc94)
다시살려주세요

**Comment by Glenn-syj** [comment]
일단 char의 자료형 값이 기본적으로 0~128이고... 계산을 하기 위해서는 char 스택만을 이용할 수 없습니다. int 스택을 새로 만들어서 시도하는 것을 추천합니다.

**Comment by ucream-sh** [comment]
인트스택을 다른 이름으로 하나 더 생성해서 풀이가 가능할 듯 합니다.
풀이되면 공유하겠습니다
