### ISSUE TITLE
파일 컨벤션 교체 검토 요청

### ISSUE THREAD

**Issue by minukHwang** [Glenn-syj/just-do-algorithms#25]
### 요청 사유
- 이클립스에서 파일 생성 후 SWEA, 백준에서 문제를 풀고 나서 다시 파일 이름을 교체하고 커밋하는 것에 불필요한 과정들이 있어 검토 요청드립니다.

### 이전 방식
```
파일명: "<Week>_<Platform>_문제번호_성함.java"
cf) Week0_SWEA_1234_손영준.java
```
- 백준: `Main.java`
- SWEA: `Solution.java`

#### 문제 사항
-  문제 해결 후, 커밋을 위해서 파일 재 생성 후 커밋 과정의 불필요함.
-  혹은 디폴트 패키지에 해당 클래스로 생성 후 각 사이트에 복붙할 때의 과정에서 매번 바꿔주어야 하는 것에 대한 어려움.

### 요청 방식
```
패키지명: "<Week>_<Platform>_문제번호_성함"
(패키지 이름을 위와 같이 적용)

📦 Week0_SWEA_1234_손영준
     └── 📄 Solution.java
```

➡ 문제 해결 후, 해당 패키지 Week00X 파일에 복붙후 바로 커밋 가능
➡ Week00X를 JavaProject로 하고 src 파일까지 커밋하는 방식이 더 편하긴 할 것 같으나 너무 위계가 많이 생길 수도 있어서, 해당 부분도 검토 부탁합니다.

**Comment by ucream-sh** [comment]
매우 공감되네요! 저는 좋은 방법이라고 생각하고 다들 괜찮으시면 이렇게 바꾸는것도 어떨까싶네요
파이썬 자동화로 생성하기도 더 쉬워질듯하네요

그리고 혹시 SWEA -> swea
백준 -> boj

이런식으로 7반 컨벤션과 같이 맞추는 건 어떻게 생각하나요? 새 이슈를 발행해야하려나..

**Comment by Glenn-syj** [comment]
음~ 이 방식이 더 좋은 것 같습니다.

WeekXXX에 대해서 패키지를 만들고, 아래 파일에는 <Platform>_<문제번호>_<이름> 형식이면 괜찮을까요?

Platform 형식에 대해서도 논의해보면 좋겠습니다. 

(1) 소문자로 작성
(2) 백준을 boj로 작성

더 편한 방식이 있다면 최대한 일찍 바꾸는 게 좋겠습니다.

**Comment by Glenn-syj** [comment]
> 매우 공감되네요! 저는 좋은 방법이라고 생각하고 다들 괜찮으시면 이렇게 바꾸는것도 어떨까싶네요 파이썬 자동화로 생성하기도 더 쉬워질듯하네요
> 
> 그리고 혹시 SWEA -> swea 백준 -> boj
> 
> 이런식으로 7반 컨벤션과 같이 맞추는 건 어떻게 생각하나요? 새 이슈를 발행해야하려나..

이 건에 대해서는 제가 이슈를 새로 발행하겠습니다.

**Comment by celestedayoung** [comment]
저도 좋은 방법이라고 생각합니다. 저는 지금 하나의 패키지 내 문제 이름으로 된 클래스를 만들어서 관리중인데 사이트에 제출하거나 스터디 커밋할 때 매번 바꾸는 게 번거롭더라고요. 위 convetnion을 따르면 개인적으로 관리하기에도 좋은 것 같습니다!

**Comment by undeadtimo** [comment]
넵 찬성합니다! 

인지하지 못하고 있었는데, 불필요한 시간 소모가 지속적으로 일어나고 있었네요.

패키지로만 구분이 되어있어도 충분히 각 문제들을 구별할 수 있을 것 같습니다.

SWEA -> swea, 백준 -> boj
이 부분도 새로 이슈가 발행될 것이긴 하지만, 영어 소문자로 통일이 된다면 커밋 작성이 한결 편해질 것 같네요.

**Comment by minukHwang** [comment]
아래와 같이 되면 워크스페이스를 애초에 `WeekXXX`로 만들 수 있긴 합니다.

```
📂 Week00X
 └── 📂 src
           └── 📦 Week0_SWEA_1234_손영준
                      └── 📄 Solution.java
                      └── 📄 Week0_SWEA_1234_손영준.pdf
```

다만, 나중에 파일 읽기가 불편할 것 같으면 위처럼 가는 것이 좋을 것 같습니다.
그리고 pdf 파일 넣을 때 어디에 넣을지도 고려 필요하겠네요.

**Comment by qkrrjsxor** [comment]
동의합니다
근데 그러면 워크스페이스를 매주마다 만들어야하나요?
저는 교수님이 주신 algorithm 워크스페이스에 Study 폴더를 따로 프로젝트로 만들고 패키지를 주차별로 관리했었는데,
매주마다 워크스페이스 생성하면 관리하기 힘들거같아요

**Comment by qkrrjsxor** [comment]
> 아래와 같이 되면 워크스페이스를 애초에 `WeekXXX`로 만들 수 있긴 합니다.
> 
> ```
> 📂 Week00X
>  └── 📂 src
>            └── 📦 Week0_SWEA_1234_손영준
>                       └── 📄 Solution.java
>                       └── 📄 Week0_SWEA_1234_손영준.pdf
> ```
> 
> 다만, 나중에 파일 읽기가 불편할 것 같으면 위처럼 가는 것이 좋을 것 같습니다. 그리고 pdf 파일 넣을 때 어디에 넣을지도 고려 필요하겠네요.

민욱이형이 예시로 든 이거는 동일한 워크스페이스 내에서 매주마다 프로젝트를 만드는건데 본문에는 워크스페이스를 만든다고 해서, 어떤 방법을 말씀하시는건가요?

**Comment by minukHwang** [comment]
> > 아래와 같이 되면 워크스페이스를 애초에 `WeekXXX`로 만들 수 있긴 합니다.
> > ```
> > 📂 Week00X
> >  └── 📂 src
> >            └── 📦 Week0_SWEA_1234_손영준
> >                       └── 📄 Solution.java
> >                       └── 📄 Week0_SWEA_1234_손영준.pdf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 다만, 나중에 파일 읽기가 불편할 것 같으면 위처럼 가는 것이 좋을 것 같습니다. 그리고 pdf 파일 넣을 때 어디에 넣을지도 고려 필요하겠네요.
> 
> 민욱이형이 예시로 든 이거는 동일한 워크스페이스 내에서 매주마다 프로젝트를 만드는건데 본문에는 워크스페이스를 만든다고 해서, 어떤 방법을 말씀하시는건가요?

수정했습니다!

**Comment by ucream-sh** [comment]
> > 아래와 같이 되면 워크스페이스를 애초에 `WeekXXX`로 만들 수 있긴 합니다.
> > ```
> > 📂 Week00X
> >  └── 📂 src
> >            └── 📦 Week0_SWEA_1234_손영준
> >                       └── 📄 Solution.java
> >                       └── 📄 Week0_SWEA_1234_손영준.pdf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 다만, 나중에 파일 읽기가 불편할 것 같으면 위처럼 가는 것이 좋을 것 같습니다. 그리고 pdf 파일 넣을 때 어디에 넣을지도 고려 필요하겠네요.
> 
> 민욱이형이 예시로 든 이거는 동일한 워크스페이스 내에서 매주마다 프로젝트를 만드는건데 본문에는 워크스페이스를 만든다고 해서, 어떤 방법을 말씀하시는건가요?

➡ Week00X를 JavaProject로 하고 src 파일까지 커밋하는 방식이 더 편하긴 할 것 같으나 너무 위계가 많이 생길 수도 있어서, 해당 부분도 검토 부탁합니다.

이 부분을 보면 동일한 워크스페이스 내에서 Week별 프로젝트로 관리하는 거인듯 합니다.

**Comment by Glenn-syj** [comment]
📂 Week00X
 └── 📂 src
           └── 📦 SWEA_1234_손영준
                      └── 📄 Solution.java
                      └── 📄 Solution.pdf
                      
             
정확히는 워크스페이스는 각자 알아서 관리하는 폴더이고,
위의 📂 Week00X 는 프로젝트입니다.
어차피 project를 쓸 거면 이런 형식이 제일 깔끔할 것 같습니다.

**Comment by minukHwang** [comment]
아니면... 깃 풀해서 브랜치 체크아웃하면서 각자 코드 보기도 가능은 할 것 같네요

**Comment by Glenn-syj** [comment]
> 아니면... 깃 풀해서 브랜치 체크아웃하면서 각자 코드 보기도 가능은 할 것 같네요

이런 방식이라면 사실 

> ```
> 📂 Week00X
>  └── 📂 src
>          └── 📦 SWEA_1234_손영준
>                       └── 📄 Solution.java
>                       └── 📄 Solution.pdf
> ```
> 
> 정확히는 워크스페이스는 각자 알아서 관리하는 폴더이고, 위의 📂 Week00X 는 프로젝트입니다. 어차피 project를 쓸 거면 이런 형식이 제일 깔끔할 것 같습니다.
> 
> 대신 이런 식으로 둘 다 Solution으로 제출하게 된다면, 띄워둔 파일이나 크롬 탭에서 어떤 문제를 보고 있는지 잘 모를 수도 있어서, 논의가 조금 필요할 것 같습니다.

이 방안으로 해도 문제가 없을 것 같습니다.

**Comment by ucream-sh** [comment]
> ```
> 📂 Week00X
>  └── 📂 src
>          └── 📦 SWEA_1234_손영준
>                       └── 📄 Solution.java
>                       └── 📄 Solution.pdf
> ```
> 
> 정확히는 워크스페이스는 각자 알아서 관리하는 폴더이고, 위의 📂 Week00X 는 프로젝트입니다. 어차피 project를 쓸 거면 이런 형식이 제일 깔끔할 것 같습니다.
> 
> 대신 이런 식으로 둘 다 Solution으로 제출하게 된다면, 띄워둔 파일이나 크롬 탭에서 어떤 문제를 보고 있는지 잘 모를 수도 있어서, 논의가 조금 필요할 것 같습니다.

오 너무 좋습니다! 저같은 경우에는 Solution으로 통일된 파일명 때문에 헷갈려서 위쪽 주석에 문제번호를 적어두긴 하는데, 패키지명으로도 보이긴 하더라고요. (사이트 제출시에는 패키지 지우느라 신경쓰이긴함)
물론 주석으로 해도 스크롤이 길어지면 안 보일 수도 있지만, 코드 리뷰 진행에 큰 영향은 없을 거라고 예상합니다.

**Comment by minukHwang** [comment]
![image](https://github.com/Glenn-syj/just-do-algorithms/assets/104661043/ebd02550-997a-46fe-a1c3-54866a70f9db)

파일 들어가설 볼때 위처럼 브레드크럼 있어서 어떤 문제 보고 있는지 확인 가능할 것 같아요

**Comment by Glenn-syj** [comment]
> 예시 1) ![image](https://private-user-images.githubusercontent.com/104661043/302849570-ebd02550-997a-46fe-a1c3-54866a70f9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzYyODgsIm5iZiI6MTcwNzI3NTk4OCwicGF0aCI6Ii8xMDQ2NjEwNDMvMzAyODQ5NTcwLWViZDAyNTUwLTk5N2EtNDZmZS1hMWMzLTU0ODY2YTcwZjlkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMzE5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDY5OTE4NmViOTk1NGYzNGQzNWNiY2U1Zjc1MjVmYmU1NGU0MmUyMDNkNmUxZTJmYzcxZTk4OGE0YmYwNjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FBvDlC2WM5EMJ6UzKJjoJ-EtbLloBHvS_2rYAyTbD68)
> 
> 예시 2) ![chrome_CNKIa1Gxv6](https://private-user-images.githubusercontent.com/104661043/302849848-54b39de1-28a9-4828-9791-fd1e651bac7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzYyODgsIm5iZiI6MTcwNzI3NTk4OCwicGF0aCI6Ii8xMDQ2NjEwNDMvMzAyODQ5ODQ4LTU0YjM5ZGUxLTI4YTktNDgyOC05NzkxLWZkMWU2NTFiYWM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMzE5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTg4ODc0OWRmMTliOGIxOGVlZmM3NjgwMTk3MWIxZGYwM2FhZmY2MGI2MjdjNzllODE0ZjllZWMyNzJiNDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pc1S0mQas4vdFvLEGbQbb0DEjWMoIg9Ywdw-wDb_THo)
> 
> 파일 들어가설 볼때 위처럼 브레드크럼 있어서 어떤 문제 보고 있는지 확인 가능할 것 같아요

맞습니다. 제가 말한 건 pdf 파일 얘기였어요! (물론 주소창에 띄워주지만) 그런데 웬만하면 그냥 둘 다 Solution 써도 될 것 같습니다.

**Comment by minukHwang** [comment]
테스트로 이번에 제가 먼저 커밋 올려 보겠습니다......!

**Comment by Glenn-syj** [comment]
컨벤션 교체 후 main에 반영하였습니다.
