### ISSUE TITLE
제출 파일 <Platform> 형식 변경 논의

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/just-do-algorithms#26]
현재 제출 파일명 컨벤션은 아래와 같습니다.

`Week000_SWEA_1234_손영준.java`

현재 swea 문제는 `SWEA`로, 백준 문제는 `백준`으로 작성되고 있는데요.
통일성 있게 각각 `swea`와 `boj`로 변경하는 제안이 있었습니다.

Ref: #25

**Comment by celestedayoung** [comment]
찬성합니다. 둘 다 소문자/영어로 통일시키는 게 좋아보이네요.

**Comment by undeadtimo** [comment]
찬성합니다.
처음 정할 때는 생각하지 못했지만, 한글로 백준을 작성하고, 영어 대문자로 SWEA를 작성하는 것이 헷갈릴 때가 있더군요.
영어 소문자인 swea와 boj로 컨벤션을 변경한다면 한결 편해질 것 같습니다.

**Comment by ucream-sh** [comment]
저도 찬성이고 다들 동의하신다면 진행시켜주시면 좋겠습니다!

처음에 컨벤션 의견을 낼 때, `SWEA`와 `백준` 이 가독성이 더 좋아 보여서 그렇게 지정된 게 좋았는데
실수를 줄이려면 변경하는게 좋을 것 같네요~

**Comment by minukHwang** [comment]
만약 패키지로 바뀌게 되면 소문자로 시작하는게 나을 것 같아서 저도 찬성입니다~

**Comment by qkrrjsxor** [comment]
저도 영어 소문자가 좋다고 생각합니다~

**Comment by Glenn-syj** [comment]
그러면 일단 패키지명과 통일성 등을 고려했을 때, <Platform> 항목은 소문자+영어로 작성하는 방식으로 변경하겠습니다.
