### ISSUE TITLE
깃허브 md에서 토글 사용하는 html 공유합니다.

### ISSUE THREAD

**Issue by ucream-sh** [Glenn-syj/just-do-algorithms#29]
```
<details>
<summary>토글 접기/펼치기</summary>
<div markdown="1">

여기다가 내용을 입력해주시면 됩니다.
토글 접기/펼치기 부분의 텍스트도 원하는 대로 수정 가능합니다. ex) 내 코드
div markdown 1 해주어야 잘 작동한다고 합니다!
여러 html들 응용도 가능할거같네요

</div>
</details>
```

코드 전문을 컬러스트립터 사이트로 게시해서 공유하려니 번거로운 점들이 있어서 토글을 이용해서 올리려고 합니다~

<details>
<summary>?</summary>
<div markdown="1">
<h1>uCanCallMeTa3k</h1>
</div>
</details>

**Comment by Glenn-syj** [comment]
너무 좋습니다! 공유해주셔서 감사해요

**Comment by undeadtimo** [comment]
md 파일을 자주 사용하는 저에게 무척 도움이 되는 정보입니다!
다음 md 파일을 작성할 때 토글을 사용하여 더 깔끔한 정리가 가능하겠네요! 감사합니다!
