### ISSUE TITLE
[ALG-001] Week001에서 봐야 할 깃/허브 이용관련 실수들

### ISSUE THREAD

**Issue by Glenn-syj** [Glenn-syj/just-do-algorithms#31]
Week001 에 발생한 깃/허브 이용 관련 실수들입니다.

![image](https://github.com/Glenn-syj/just-do-algorithms/assets/65771798/303b0e4f-ca3d-4bb8-95fe-f87bde9d7e2f)

## DON'T MERGE
 
- 제가 아닌 다른 collaborator 분들은 merge하지 말아 주시길 바랍니다.
- 사실 여러분은 collaborator가 해제 되어도 pork-clone-PR 과정을 거치기에 별 무리 없이 사용할 수 있긴 합니다.
  -> 즉, 이런 일이 계속 발생하면 collaborator에서 모두 제외할 가능성이 높습니다.

![image](https://github.com/Glenn-syj/just-do-algorithms/assets/65771798/90fc6a9a-b790-4a69-92cc-7d138f98a6d0)

## CHECK THE HEAD/BASE AGAIN

- upstream repo와 본인의 porked repo는 물론, 각 repo의 브랜치까지 잘 확인해주세요.
- 자기는 아무 것도 잘못 설정한 게 없다? 그렇지 않습니다! (git 이용 과정에서도 잘 확인하기!)
- 커밋할 때 자신의 porked repo/your branch 인지 다시 확인해주세요.
- PR 올릴 때도 자신의 porked repo/your branch에서 upstream repo/your branch로 향하는지 잘 확인해주세요.
 -> 이걸 잘 체크하려고 저 빼고 merge하지 말라는 겁니다!
 -> 실제로 위 merge 에서는 porked repo/your branch에서 바로 upstream repo/main으로 merge가 되었습니다.

<br/>
<br/>

**그래도 지금 실수하는 게 더 큰 상황에서 실수하는 것 보다 낫습니다. 잘 숙지해주세요!**

**Comment by qkrrjsxor** [comment]
확인했습니다 다음부터는 approve만 하고 merge는 안할게요!!

**Comment by undeadtimo** [comment]
확인했습니다. commit과 merge에 관한 실수를 하지 않도록 더욱 주의하겠습니다.

**Comment by minukHwang** [comment]
확인했습니다. 주의하도록 하겠습니다!

**Comment by celestedayoung** [comment]
네 확인했습니다.

**Comment by Glenn-syj** [comment]
모두 확인했으니 이슈는 close하겠습니다!
