### ISSUE TITLE
Week 3 problems by Glenn-syj

### ISSUE THREAD

**Issue by ucream-sh** [Glenn-syj/just-do-algorithms#42]
💡 건택이는 정처기로 인해서 필수 문제는 2개만 풀어오면 됨…!!

### 공통 과제

- [ ]  SWEA 1231 중위순회 (← 트리에 대해서 배우고 진행해보세요!)
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV140YnqAIECFAYD
- [ ]  백준 24511 큐스택 (← 큐와 스택의 복습에 목적을 둬보세요!)
https://www.acmicpc.net/problem/24511
- [ ]  백준 11729 하노이의 탑 (← 재귀를 이해해보세요!)
https://www.acmicpc.net/problem/11729
- [ ]  백준 11279 최대 힙 (← 우선순위 큐의 힙을 통한 구현을 이해하는 것에 목적을 둬보세요!)
https://www.acmicpc.net/problem/11279

### 분할 과제

**하**

- [ ]  SWEA 1234 비밀번호
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14_DEKAJcCFAYD
- [ ]  SWEA 1221 GNS
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14jJh6ACYCFAYD
- [ ]  SWEA 1961 숫자배열회전
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5Pq-OKAVYDFAUq

**중**

- [ ]  SWEA 1220 Magnetic
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14hwZqABsCFAYD
- [ ]  백준 2527 직사각형
https://www.acmicpc.net/problem/2527
- [ ]  SWEA 1244 최대 상금 **손영준**
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV15Khn6AN0CFAYD

**상 (아닐수도)**

- [ ]  백준 2156 포도주 시식 **송창용**
https://www.acmicpc.net/problem/2156
- [ ]  백준 2805 나무 자르기 **유서현**
https://www.acmicpc.net/problem/2805
- [ ]  백준 1725 히스토그램
https://www.acmicpc.net/problem/1725

**Comment by Glenn-syj** [comment]
이번 주도 깃헙에 올려주셔서 감사합니다!!

**Comment by ucream-sh** [comment]
3주차 고생많으셨습니다!
