### ISSUE TITLE
[SWEA 1230] 암호문3 반례 찾아주세요.

### ISSUE THREAD

**Issue by celestedayoung** [Glenn-syj/just-do-algorithms#49]
해당 문제에 대해서 직접 테스트 케이스를 만들어 돌려보았을 때 add, insert, delete 모두 정상적으로 수행되는데 반례가 있을까요?
제가 이해한 바에 의하면, 예를 들어 1 2 3 4 5라는 암호문에 대하여

> `A 99 98`을 수행하면 1 2 3 4 5 99 98
> `I 2 2 99 98`을 수행하면 1 2 3 9 98 4 5 
> `D 3 1`을 수행하면 1 2 3 4

위와 같이 출력되어야 한다고 이해했습니다. 
(각 명령문이 연속적으로 수행된 것이 아니라 초기 상태에 대하여 각각 적용한 경우입니다.)

문제 링크: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14zIwqAHwCFAYD

<details>
<summary>작성한 코드</summary>

```java
package swea_1230_암호문3;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;


public class Solution {
	
	public static void main(String[] args) {
		
		Scanner sc = new Scanner(System.in);
		
		for (int t = 1; t <= 10; t++) {
			int passwordLength = sc.nextInt();
			
			SinglyLinkedList passwords = new SinglyLinkedList();
			
			for (int i = 0; i < passwordLength; i++) {
				passwords.addLast(sc.next());
			}
			
			int orderLength = sc.nextInt();
			
			int orderCnt = 0;
			
			while(orderCnt < orderLength) {
				
				String inputOrder = sc.next();
				
				if (inputOrder.equals("I")) {
					
					int insertIdx = sc.nextInt();
					int insertNum = sc.nextInt();
					
					for (int i = 0; i < insertNum; i++) {
						passwords.add(insertIdx, sc.next());
						insertIdx++;
					}
					orderCnt++;
					
				} else if (inputOrder.equals("D")) {
					
					int deleteIdx = sc.nextInt();
					int deleteNum = sc.nextInt();
					
					for (int d = 0; d < deleteNum; d++) {
						passwords.remove(deleteIdx);
					}
					orderCnt++;
					
				} else if (inputOrder.equals("A")) {
					
					int addNum = sc.nextInt();
					for (int a = 0; a < addNum; a++) {
						passwords.addLast(sc.next());
					}
					orderCnt++;
				}		
			}
			System.out.printf("#%d", t);
			passwords.printItem(10);
		}
	}
	
	// Node Class
	static class Node {
		String data;
		Node link;
		
		Node() {}
		Node(String data) {
			this.data = data;
		}
	}
		
	// Singly Linked List Class
	static class SinglyLinkedList {
		
		Node head;
		int size;
		int idx;
		
		SinglyLinkedList() {
			head = new Node();
		}
		
		// [삽입]: 기존의 연결을 끊기 전에 새로 삽입하고자 하는 노드를 먼저 연결시켜야 한다.
		// 가장 앞에 삽입
		void addFirst(String data) {
			Node newNode = new Node(data);
			
			newNode.link = head.link;
			head.link = newNode;
			
			size++;
		}
		
		// 가장 뒤에 삽입
		void addLast(String data) {
			Node newNode = new Node(data);
			
			Node curr = head;
			while(curr.link != null) {
				curr = curr.link;
			}
			
			curr.link = newNode;
			size++;
		}
		
		// 중간에 삽입: 지정한 idx 뒤에 삽입
		void add(int idx, String data) {
			
			if (idx < 0 || size < idx) {
				System.out.println("삽입할 수 없는 위치입니다.");
				return;
			}
			
			Node curr = head;
			for (int i = 0; i <= idx; i++) {
				curr = curr.link;
			}
			
			Node newNode = new Node(data);
			newNode.link = curr.link;
			curr.link = newNode;
			
			size++;
			
		}
		
		// [삭제]: 연결만 끊어주면 더 이상 접근할 수 없는 노드는 GC가 삭제해준다.
		// 특정 idx에 해당하는 노드 뒤에 있는 노드를 삭제
		void remove(int idx) {
			if (idx < 0 || getSize() <= idx) {
				System.out.println("삭제할 수 있는 범위를 벗어났습니다.");
				return;
			}
			Node curr = head;
			
			for (int i = 0; i <= idx; i++) {
				curr = curr.link;
			}
			// 반복문이 끝나면 curr는 삭제할 노드 앞의 노드를 가리킨다.
			curr.link = curr.link.link;
			
			size--;
		}
		
		// [조회]
		// 모든 데이터 조회
		void printList() {
			Node curr = head.link;
			while (curr != null) {
				System.out.print(" " + curr.data);
				curr = curr.link;
			}
			System.out.println();
		}
		
		// 처음부터 특정 idx까지 데이터 조회
		void printItem(int idx) {
			Node curr = head.link;
			for (int i = 0; i < idx; i++) {
				System.out.print(" "+ curr.data);
				curr = curr.link;
			}
			System.out.println();
			
		}
		
		int getSize() {
			Node curr = head;
			int size = 0;
			while (curr.link != null) {
				curr = curr.link;
				size++;
			}
			return size;
		}
	}

}

```
</details>

**Comment by Glenn-syj** [comment]
Insert의 경우, 0번째에 추가하는 경우를 고려해보셨나요?

**Comment by celestedayoung** [comment]
> Insert의 경우, 0번째에 추가하는 경우를 고려해보셨나요?

I 0 2 99 98의 경우에도 결국 가장 앞에는 요소를 추가할 수 없는 것 아닌가요? 가장 앞에 요소를 추가하는 경우 I가 어떻게 주어지는지 궁금합니다.

**Comment by minukHwang** [comment]
문제에서 10개만 출력하라고 했는데 혹시 그건 고려가 된 건가요?

**Comment by Glenn-syj** [comment]
> > Insert의 경우, 0번째에 추가하는 경우를 고려해보셨나요?
> 
> I 0 2 99 98의 경우에도 결국 가장 앞에는 요소를 추가할 수 없는 것 아닌가요? 가장 앞에 요소를 추가하는 경우 I가 어떻게 주어지는지 궁금합니다.

`1 2 3 4 5` 라는 암호문에 대하여
`I 0 2 100 100` 을 실행하면
`100 100 1 2 3 4 5` 가 됩니다

input.txt 파일에 'I 0'으로 검색해보면 해당 명령들이 있습니다.

**Comment by celestedayoung** [comment]
> 문제에서 10개만 출력하라고 했는데 혹시 그건 고려가 된 건가요?

네! 고려했는데 output 값의 맨 처음부터 값이 다르더라고요.

**Comment by minukHwang** [comment]
문제에서 1번째가 index 0입니다. 지금 insert delete할 때 1번째면 index 1이후로 생각해서 틀린 것 같아요

**Comment by Glenn-syj** [comment]
문제가 불친절해서 생기는 문제 같은데...

1. I(삽입) x, y, s : 앞에서부터 x번째 암호문 바로 다음에 y개의 암호문을 삽입한다. s는 덧붙일 암호문들이다.[ ex) I 3 2 123152 487651 ]
2. D(삭제) x, y : 앞에서부터 x번째 암호문 바로 다음부터 y개의 암호문을 삭제한다.[ ex) D 4 4 ]
3. A(추가) y, s : 암호문 뭉치 맨 뒤에 y개의 암호문을 덧붙인다. s는 덧붙일 암호문들이다. [ ex) A 2 421257 796813 ]

에서, I의 경우 dummy head를 따로 두신다면  head(0번) -> node(1번) -> node(2번) 이렇게 생각하셔야 할 겁니다.

**Comment by celestedayoung** [comment]
> 문제가 불친절해서 생기는 문제 같은데...
> 
> 1. I(삽입) x, y, s : 앞에서부터 x번째 암호문 바로 다음에 y개의 암호문을 삽입한다. s는 덧붙일 암호문들이다.[ ex) I 3 2 123152 487651 ]
> 2. D(삭제) x, y : 앞에서부터 x번째 암호문 바로 다음부터 y개의 암호문을 삭제한다.[ ex) D 4 4 ]
> 3. A(추가) y, s : 암호문 뭉치 맨 뒤에 y개의 암호문을 덧붙인다. s는 덧붙일 암호문들이다. [ ex) A 2 421257 796813 ]
> 
> 에서, I의 경우 dummy head를 따로 두신다면 head(0번) -> node(1번) -> node(2번) 이렇게 생각하셔야 할 겁니다.

삽입, 삭제를 해야 할 위치를 제가 잘못 이해하고 있었네요.. 설명 감사합니다!

**Comment by celestedayoung** [comment]
> 문제에서 1번째가 index 0입니다. 지금 insert delete할 때 1번째면 index 1이후로 생각해서 틀린 것 같아요

조언 참고해서 수정했더니 통과했네요. 감사합니다!

**Comment by Glenn-syj** [comment]
원래는 각 입력에 대한 범위가 주어지는 게 맞습니다. 이건 문제가 불친절한 탓으로... 입력을 뜯어서 반례를 찾아보고 코드를 다시 들여다보는 연습을 했다고 생각하는 게 마음 편합니다...

**Comment by Glenn-syj** [comment]
특히 해당 문제는 사실 addLast 와 같이 뒤에 추가하는 method는 구현할 필요도 없더라구요.
'A'를 입력받으면 넘어가도 풀리는 문제라, 신경쓰지 못한 부분이 꽤 있어 보입니다. 

디버깅 과정에 의의를 두는 게 맞아보입니다.

**Comment by celestedayoung** [comment]
> 원래는 각 입력에 대한 범위가 주어지는 게 맞습니다. 이건 문제가 불친절한 탓으로... 입력을 뜯어서 반례를 찾아보고 코드를 다시 들여다보는 연습을 했다고 생각하는 게 마음 편합니다...
> 
> 특히 일상과 관련된 문제에서, 무조건 0번째에서 시작한다거나 1번째에서 시작한다는 보장은 없습니다. (컴퓨터적으로 사고하면 `0번째`가 맞지만, 사실 `0등/0번 타자/0번째 암호문` 등은 존재하지 않습니다.)
> 
> 따라서 이러한 조건에 대해서는 문제에서 제시해주는 게 맞습니다. 만약 그렇지 않다면... 스스로 input.txt를 뜯어봐야합니다.

input.txt를 잘 살펴보는 습관을 가져야겠네요!
