### ISSUE TITLE
swea_2930_힙 문제 이해를 도와주실분?

### ISSUE THREAD

**Issue by ucream-sh** [Glenn-syj/just-do-algorithms#60]
```java
	static void swap(int a, int b) {
		// a와 b를 입력받으면 스왑 // 스태틱으로해야 직접 스왑할수있음
		int temp = heap[a];
		heap[a] = heap[b];
		heap[b] = temp;
	}

	static void heapPush(int data) { // 연산1
		heap[++size] = data; // 힙의 맨끝에넣어서 완전이진트리를 유지해야함
		int child = size; // 8이면
		int parent = size / 2; // 4

		while (parent > 0 && heap[parent] < heap[child]) { // 부모가 0이아니고 자식보다 작으면 아닐때까지 반복문
			swap(parent, child); // 이렇게 값을 직접 바꾸는게 아니고 인덱스를 바꾸는거였나
			child = parent; // 자식인덱스를 부모인덱스로 바꿔주고 // 4
			parent = child / 2; // 2
		}

	} // heapPush()
```

제가 실습 때를 참고해서 구현한 메서드들입니다. 
while문 안에서 `child = parent;` 와 `parent = child / 2;` 부분의 값들을 넣어줄 때는 왜 swap() 할 때처럼 temp 없이도 잘 돌아가는건지 궁금합니다!

마찬가지로 `heapPop()` 메서드에서도 `parent = child;` 와 `child = parent * 2;` 부분도 눈으로 봐서는 감이 잘 오지 않더라고요.

값을 넣어보면서 직접 그려보는게 좋을까요?

**Comment by Glenn-syj** [comment]
1. child와 parent는 서로 자리를 바꾸는 swap이 아니기에, 중간에 값을 할당할 tmp가 필요하지 않습니다. (그냥 다른 값을 할당할 뿐입니다.)
2. 직접 표나 그림을 그려서 확인해봐도 좋겠습니다.

**Comment by ucream-sh** [comment]
> 1. child와 parent에의 할당은 서로 자리를 바꾸는 swap이 아니기에, 중간에 값을 할당할 tmp가 필요하지 않습니다. (그냥 다른 값을 할당할 뿐입니다.) 쉽게 생각하면, child = parent 에서 해당 할당 이전의 child 값은 날아갑니다.
> 2. 직접 표나 그림을 그려서 확인해봐도 좋겠습니다.

할당 이전의 값이 날라간다는 표현을 들으니 느낌이 잘 오네요!! 8->4에서 4->2로 트리를 한 칸 올라갔으니 부모노드도 한 칸 올려주는 느낌으로 이해했습니다. 감사합니다 :)
