### ISSUE TITLE
StringTokenizer 사용 중 질문 드립니다!

### ISSUE THREAD

**Issue by clare-u** [Glenn-syj/just-do-algorithms#87]
지난 번 도움도 감사드립니다.

이번주의 문제인 토마토를 제대로 풀이하기 위해
바킹독 블로그의 [[[실전 알고리즘] 0x09강 - BFS](https://blog.encrypted.gg/941)](https://blog.encrypted.gg/941) 의 추천 문제를 풀이 중입니다. 확실히 bfs 알고리즘이라 그런지 목록에 토마토 문제도 있더라고요!

1단계 문제인 그림 문제는 풀이에 성공했는데,
2단계 문제인 [boj_2178_미로탐색](https://www.acmicpc.net/problem/2178)는 입력을 받는 부분에서 헤메고 있어 도움 부탁드립니다.

인풋으로 들어오는 값들이 101111 이런식으로 이어서 들어오기 때문에 
`StringTokenizer st = new StringTokenizer(sc.next(), "");` 이렇게 구분자없이 모두 토큰화해서 하나씩 받으려고 했는데요,

```
for (int n = 0; n < N; n++) {
			StringTokenizer st = new StringTokenizer(sc.next(), "");
			for (int m = 0; m < M; m++) {
				maze[n][m] = st.nextToken();
			}
		}
```

이렇게 코드를 돌리니 

```
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:347)
	at boj_2178_미로탐색.Main.main(Main.java:37)
```

라는 오류와 마주해버렸습니다.

반복문이 문제일지 아니면 토크나이저 관련 문법이 문제일지 도움 부탁드립니다!

**Comment by celestedayoung** [comment]
maze 배열의 type이 무엇인가요??

**Comment by clare-u** [comment]
+ maze[][]의 타입은 String 입니다.

**Comment by celestedayoung** [comment]
구분자 없는 String의 경우 StringTokenizer보단 String에 .split()을 사용하거나 .charAt()으로 접근하는 것이 좋을 것 같습니다!

**Comment by clare-u** [comment]
> 구분자 없는 String의 경우 StringTokenizer보단 String에 .split()을 사용하거나 .charAt()으로 접근하는 것이 좋을 것 같습니다!

오 감사드립니다! charAt은 써본 경험이 많으니 split으로 연습해보겠습니다. 풀이해보고 내일 이슈 close 하겠습니다 ㅎㅎ

**Comment by Glenn-syj** [comment]
추가로 Problem Solving에 있어서, split() method는 String[] 배열을 반환하기 때문에 String type에 대한 생성 cost와 배열에 대한 생성 cost가 모두 들게 된다는 점에도 유의해주세요~

**Comment by clare-u** [comment]
> 추가로 Problem Solving에 있어서, split() method는 String[] 배열을 반환하기 때문에 String type에 대한 생성 cost와 배열에 대한 생성 cost가 모두 들게 된다는 점에도 유의해주세요~

처음에 시간 초과가 떴었는데 그 이유때문에 더 그랬겠네요! 제대로 따져보지 않고 반복문을 쓰는 양식을 외워서 사용하려 했는데 덕분에 이해가 깊어져서 좋습니다.  참조형에 대한 공부는 해도해도 끝이 없네요😊

성원에 힘을 입어 미로탐색과 토마토 두 문제 모두 solve했습니다 ! 6주차 스터디도 힘내보겠습니다 ㅎㅎ
